language: python
python:
  - "2.7"

env:
  - SQLALCHEMY_DATABASE_URI="sqlite://"
  - SQLALCHEMY_DATABASE_URI="postgres://postgres@localhost:5432/abilian_core"
  - SQLALCHEMY_DATABASE_URI="mysql://root@localhost/abilian_core"

matrix:
  allow_failures:
    - env: SQLALCHEMY_DATABASE_URI="mysql://root@localhost/abilian_core"
  fast_finish: true

services:
  - redis-server

addons:
  postgresql: "9.3"

# Install OS-level dependencies
before_install:
 - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
 - sudo apt-add-repository -y ppa:chris-lea/node.js
 - sudo apt-get update
 - sudo apt-get install -y poppler-utils nodejs
 - sudo npm install -g less

# Install Python dependencies
install:
  - pip install -r dev-requirements.txt

# Create DB
before_script:
  - psql -c 'create database abilian_core;' -U postgres

# Run tests
script:
  - py.test --tb=short -q --cov abilian abilian tests
  - sphinx-build -W -b html docs/ docs/_build/

# Report coverage
after_success:
  - coveralls
